### ISSUE TITLE
Not working on turbo anymore :( 

### ISSUE THREAD

**Issue by markomitranic** [destacks/core-ts#1]
Hey there, the server-cli-only isn't working with `dev --turbo` anymore. It always throws.

**Comment by 4lm** [comment]
Hi @markomitranic,

Thank you for reporting. I created a new branch to investigate, added an [example Next.js project](https://github.com/destacks/core-ts/tree/fix-dev-with-turbo-flag-throwing/packages/server-cli-only/examples/next-js-app), and tested Next.js with `next dev --turbo`. I don't have any issues using Turbopack. Everything works as expected.

Can you further describe your issue? Some error output (in a Gist) would be helpful.

Maybe also look at my example project and re-check at your end.

**Comment by markomitranic** [comment]
Hey @4lm thanks for the response!

True, perhaps I am using it wrong in some way. I have been using it since you released it without any issues up until recently. I will fork the example and try to open a PR with a reproduction :)

**Comment by markomitranic** [comment]
@4lm I just did a tiny bit of additional testing, it would seem that running turbo no longer imports the empty file and instead imports the file with the if statement.

I've copied the if statement into my codebase, just to verify exactly what it resolves to (even tho it shouldn't be running in the first place):
```ts
  console.log(typeof process === "undefined");  // false
  console.log(typeof process.env === "undefined");  // false
  console.log(process.env.RUNNING_IN_CLI !== "true");  // true
```

So, running it with `RUNNING_IN_CLI=true npm run dev --turbo` works just fine it seems, and serves as a temporary solution, but it is far from ideal of course.

**Comment by 4lm** [comment]
Hi @markomitranic,

I solved the issue and published a new version. Just update, and everything should work as expected.

**Context:** `server-cli-only` uses like `server-only` so-called "poisoned imports" to break things on compile-time so as not to leak sensitive data to the front end. On edge `turbopack` now weirdly defaults to the `browser` runtime directive instead of staying with the `react-server` runtime as before with Webpack:

- Webpack: `npm run dev` on route `/api` uses `react-server` runtime
- Webpack: `npm run dev` on route `/api/edge` uses `react-server` runtime
- Turbopack: `npm run dev:turbo` on route `/api` uses `react-server` runtime
- Turbopack: `npm run dev:turbo` on route `/api/edge` uses `browser` runtime (throws an error because React Client Components use the same runtime key and `server-cli-only` therefore throws an error on )

I looked deeper and realized that `turbopack` sets the runtime to `edge-light` or `worker` if those exports are given instead of using `browser` as the runtime key. Now, using `server-cli-only` with Next.js and Vercel, the behavior should be:

- Webpack: `npm run dev` on route `/api` uses `react-server` runtime
- Webpack: `npm run dev` on route `/api/edge` uses `react-server` runtime
- Turbopack: `npm run dev:turbo` on route `/api` uses `react-server` runtime
- Turbopack: `npm run dev:turbo` on route `/api/edge` uses `edge-light` runtime (no error anymore, because `server-cli-only` passes this through)

If you like, look at the updated `package.json` of `server-cli-only`. I think this will help to better understand how things work.

**PS:** I removed the whole env var usage I introduced before for the "node" server runtime because we now have `deno` and `bun` as supported server runtime, and the runtime keys should protect enough on build time. But this has nothing to do with your case, and setting the environment variable for the "node" runtime - as you suggested - should have had no effect while running `npm run dev:turbo` because we would never have hit the "node" runtime directive because the "react-server" and "browser" would have still been used. This whole topic seems a little implicit and hard to grasp 😉

**Comment by markomitranic** [comment]
Thanks! I've seen the package.json changes yesterday and it all made sense. I was aware of the export pattern but did not know it goes under "poisoned imports". 

By the way, how did you find out which runtime uses which keyword? I couldn't find any relevant docs when I searched, although I must admit I didn't search too deeply, so I assume you have a way to log it somehow?

**Comment by 4lm** [comment]
You're welcome! Yes, finding information on this topic seems quite scattered and sparse. For more info, look at [this section](https://github.com/destacks/core-ts/tree/main/packages/server-cli-only#lookout-places-for-additional-runtime-keys-in-the-future) in the readme of `server-cli-only`. There, I linked to the WinterCG spec proposal and the implementation of runtime keys via "conditional exports" in `react-dom`'s `package.json`.

Considering the spec proposal and `react-dom`'s `package.json`, I included all relevant runtime keys, which can be found in the WinterCG spec proposal and are also implemented in `react-dom`. Additionally, I've added the Netlify Edge runtime ("netlify"), which now supports RSC on the edge to the best of my knowledge.

Please note that I omitted the runtime key "worker" present in `react-dom`'s "conditional exports" because it isn't in the WinterCG spec proposal. Reading through the commit messages in `react-dom`'s, it isn't clear to me if the "worker" runtime key isn't also used to indicate code that is run on the client side in the browser via Service Workers (the runtime key "worker" is also not present in the WinterCG spec proposal).

Not including "worker" as a runtime keyword seems to be OK for your use-case (Next.js + Turbopack) because I could identify in the Rust code implementation of Next.js's `@next-swc` package ("responsible for swc compilation customized for next.js") that either the runtime key "edge-light" or "worker" seem to indicate a Next.js Edge runtime. And my tests showed that this seems to be the case. Hence, the "worker" runtime key could be left out until further clarification as long as "edge-light" is used in the conditional exports of `server-cli-only`.
